apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - reloader.yaml

patches:
  - path: statefulset-reloader-label.yaml
    target:
      kind: StatefulSet
      name: bitsong

