apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitsong-fullnode

resources:
  - 01-namespace.yaml
  - 03-statefulset.yaml
  - 04-service-lb.yaml
  - 05-service-headless.yaml
  #- job  

generatorOptions:
  disableNameSuffixHash: true

replicas:
  - name: bitsong
    count: 1

images:
  - name: mycuriosity/bitsong
    newTag: latest
  - name: busybox
    newTag: "1.36"

configMapGenerator:
  - name: bitsong-config
    files:
      - config/app.toml
      - config/client.toml
      - config/config.toml

  - name: bitsong-init
    files:
      - init.sh=scripts/init.sh
