apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 03-statefulset.yaml
  - 04-service-lb.yaml
  - 05-service-headless.yaml

configMapGenerator:
  - name: bitsong-config
    files:
      - config/app.toml
      - config/config.toml
      - config/client.toml
    options:
      disableNameSuffixHash: false

  - name: bitsong-init
    files:
      - scripts/init.sh
    options:
      disableNameSuffixHash: false